export const aliProductInfoExp1 = {
  ae_item_sku_info_dtos: {
    ae_item_sku_info_d_t_o: [
      {
        sku_attr: '14:193#Single Camera',
        offer_sale_price: '16.12',
        sku_id: '12000038176637560',
        price_include_tax: false,
        currency_code: 'USD',
        sku_price: '33.59',
        offer_bulk_sale_price: '16.12',
        sku_available_stock: 28,
        id: '14:193#Single Camera',
        ae_sku_property_dtos: {
          ae_sku_property_d_t_o: [
            {
              sku_property_value: 'black',
              sku_image: 'https://ae01.alicdn.com/kf/Sf873ff6e1c3447d785c166f48891080dy.jpg',
              sku_property_name: 'Color',
              property_value_definition_name: 'Single Camera',
              property_value_id: 193,
              sku_property_id: 14,
            },
          ],
        },
      },
      {
        sku_attr: '14:29#Dual Camera',
        offer_sale_price: '17.54',
        sku_id: '12000038176637559',
        price_include_tax: false,
        currency_code: 'USD',
        sku_price: '36.55',
        offer_bulk_sale_price: '17.54',
        sku_available_stock: 38,
        id: '14:29#Dual Camera',
        ae_sku_property_dtos: {
          ae_sku_property_d_t_o: [
            {
              sku_property_value: 'WHITE',
              sku_image: 'https://ae01.alicdn.com/kf/S7643a090993648e393cc95a073ca6eeaT.jpg',
              sku_property_name: 'Color',
              property_value_definition_name: 'Dual Camera',
              property_value_id: 29,
              sku_property_id: 14,
            },
          ],
        },
      },
    ],
  },
  ae_multimedia_info_dto: {
    image_urls:
      'https://ae01.alicdn.com/kf/S9057f3fa99c84371b768d2b4df70c32b6.jpg;https://ae01.alicdn.com/kf/S96bd15bcbb764c41918565cf97a0561et.jpg;https://ae01.alicdn.com/kf/Sdc63638fcc98483c9ffea78e1f045d8bl.jpg;https://ae01.alicdn.com/kf/Sc936b75b5fbc4ffbbd141577ab5e7ea3y.jpg;https://ae01.alicdn.com/kf/Se404cdbf83f24730ba3a99d98df08c20e.jpg;https://ae01.alicdn.com/kf/S064fd4e449054c8091cc648ba2f0d01ba.jpg',
  },
  package_info_dto: {
    package_width: 16,
    package_height: 6,
    package_length: 21,
    gross_weight: '0.288',
    package_type: false,
    product_unit: 100000015,
  },
  logistics_info_dto: {
    delivery_time: 7,
    ship_to_country: 'US',
  },
  product_id_converter_result: {
    main_product_id: 1005006749040149,
    sub_product_id: '{"US":3256806562725397}',
  },
  ae_item_base_info_dto: {
    mobile_detail:
      '{"version":"2.0.0","moduleList":[{"type":"text","data":{"content":"Description:","style":{"paddingLeft":16,"paddingRight":16,"paddingTop":10,"paddingBottom":10,"fontSize":14,"fontWeight":"regular","align":"left","color":"#666666","fontFamily":"OpenSans","backgroundColor":"#FFFFFF"}}},{"type":"text","data":{"content":"Professional Drone E88 4K Wide-Angle HD 1080P Camera WiFi FPV Height Hold Foldable RC Drone Quadrotor Helicopter Children\'s Toys","style":{"paddingLeft":16,"paddingRight":16,"paddingTop":10,"paddingBottom":10,"fontSize":14,"fontWeight":"regular","align":"left","color":"#666666","fontFamily":"OpenSans","backgroundColor":"#FFFFFF"}}},{"type":"text","data":{"content":"Frequency: 2.4G","style":{"paddingLeft":16,"paddingRight":16,"paddingTop":10,"paddingBottom":10,"fontSize":14,"fontWeight":"regular","align":"left","color":"#666666","fontFamily":"OpenSans","backgroundColor":"#FFFFFF"}}},{"type":"text","data":{"content":"Channel: 4CH","style":{"paddingLeft":16,"paddingRight":16,"paddingTop":10,"paddingBottom":10,"fontSize":14,"fontWeight":"regular","align":"left","color":"#666666","fontFamily":"OpenSans","backgroundColor":"#FFFFFF"}}},{"type":"text","data":{"content":"Quadcopter Battery: (Included)","style":{"paddingLeft":16,"paddingRight":16,"paddingTop":10,"paddingBottom":10,"fontSize":14,"fontWeight":"regular","align":"left","color":"#666666","fontFamily":"OpenSans","backgroundColor":"#FFFFFF"}}},{"type":"text","data":{"content":"Transmitter Battery: 3x 1.5 AA Battery (NOT Included)","style":{"paddingLeft":16,"paddingRight":16,"paddingTop":10,"paddingBottom":10,"fontSize":14,"fontWeight":"regular","align":"left","color":"#666666","fontFamily":"OpenSans","backgroundColor":"#FFFFFF"}}},{"type":"text","data":{"content":"Features:","style":{"paddingLeft":16,"paddingRight":16,"paddingTop":10,"paddingBottom":10,"fontSize":14,"fontWeight":"regular","align":"left","color":"#666666","fontFamily":"OpenSans","backgroundColor":"#FFFFFF"}}},{"type":"text","data":{"content":"- With foldable arms, small size, easy to carry.","style":{"paddingLeft":16,"paddingRight":16,"paddingTop":10,"paddingBottom":10,"fontSize":14,"fontWeight":"regular","align":"left","color":"#666666","fontFamily":"OpenSans","backgroundColor":"#FFFFFF"}}},{"type":"text","data":{"content":"- With altitude hold mode function provides stable flight.","style":{"paddingLeft":16,"paddingRight":16,"paddingTop":10,"paddingBottom":10,"fontSize":14,"fontWeight":"regular","align":"left","color":"#666666","fontFamily":"OpenSans","backgroundColor":"#FFFFFF"}}},{"type":"text","data":{"content":"- With wifi function can be connected APP, APK system to take pictures, video, real-time transmission through the phone camera image.","style":{"paddingLeft":16,"paddingRight":16,"paddingTop":10,"paddingBottom":10,"fontSize":14,"fontWeight":"regular","align":"left","color":"#666666","fontFamily":"OpenSans","backgroundColor":"#FFFFFF"}}},{"type":"text","data":{"content":"- There have 2 cameras can be choose. With 1080P or 4K wide angle camera give wide high denfinition pictures and video.","style":{"paddingLeft":16,"paddingRight":16,"paddingTop":10,"paddingBottom":10,"fontSize":14,"fontWeight":"regular","align":"left","color":"#666666","fontFamily":"OpenSans","backgroundColor":"#FFFFFF"}}},{"type":"text","data":{"content":"- With Headless Mode, no need to adjust the position of aircraft before flying .","style":{"paddingLeft":16,"paddingRight":16,"paddingTop":10,"paddingBottom":10,"fontSize":14,"fontWeight":"regular","align":"left","color":"#666666","fontFamily":"OpenSans","backgroundColor":"#FFFFFF"}}},{"type":"text","data":{"content":"- With One key to return function makes it easily to find the way home.","style":{"paddingLeft":16,"paddingRight":16,"paddingTop":10,"paddingBottom":10,"fontSize":14,"fontWeight":"regular","align":"left","color":"#666666","fontFamily":"OpenSans","backgroundColor":"#FFFFFF"}}},{"type":"text","data":{"content":"- Trajectory Flight. Draw a fligh way on the screen, and the drone would conduct an autonomous flight along the designated way.","style":{"paddingLeft":16,"paddingRight":16,"paddingTop":10,"paddingBottom":10,"fontSize":14,"fontWeight":"regular","align":"left","color":"#666666","fontFamily":"OpenSans","backgroundColor":"#FFFFFF"}}},{"type":"image","data":{"url":"https://ae01.alicdn.com/kf/S0c07c33d4f2b4eeea504bda870e792933.jpg","style":{"width":1000,"height":1000}}},{"type":"image","data":{"url":"https://ae01.alicdn.com/kf/S32f39c26892b465daa120c98fca02e52y.jpg","style":{"width":1000,"height":1000}}},{"type":"image","data":{"url":"https://ae01.alicdn.com/kf/S3188d64a9d7c49b0a56a6c2b9463c7b1B.jpg","style":{"width":1000,"height":1000}}},{"type":"image","data":{"url":"https://ae01.alicdn.com/kf/S17bc65e466684fc0b6711e33a1fd28d8B.jpg","style":{"width":1000,"height":1000}}},{"type":"image","data":{"url":"https://ae01.alicdn.com/kf/S4c84aef1c7ff4253b5e1dbe066414be5Y.jpg","style":{"width":1000,"height":1000}}},{"type":"image","data":{"url":"https://ae01.alicdn.com/kf/Sf3b6e7b6344f4338abc664d7d055931eW.jpg","style":{"width":1000,"height":1000}}}]}',
    subject:
      "Professional Drone E88 4K Wide-Angle HD 1080P Camera WiFi FPV Height Hold Foldable RC Drone Quadrotor Helicopter Children's Toys",
    evaluation_count: '629',
    sales_count: '5000+',
    product_status_type: 'onSelling',
    avg_evaluation_rating: '3.7',
    currency_code: 'CNY',
    category_id: 200003876,
    product_id: 1005006749040149,
    detail:
      '<div class="detailmodule_html"><div class="detail-desc-decorate-richtext"><p><span style="color:rgb(25, 25, 25);font-size:20px;font-family:&quot;Open Sans&quot;, Roboto, Arial, Helvetica, sans-serif, SimSun">Description:</span></p><p><span style="color:rgb(25, 25, 25);font-size:20px;font-family:&quot;Open Sans&quot;, Roboto, Arial, Helvetica, sans-serif, SimSun">Professional Drone E88 4K Wide-Angle HD 1080P Camera WiFi FPV Height Hold Foldable RC Drone Quadrotor Helicopter Children\'s Toys</span></p></div></div>\r\n<div class="detailmodule_html"><div class="detail-desc-decorate-richtext"><p style="line-height:inherit;color:rgb(0, 0, 0);margin:0px;margin-bottom:0px;margin-top:0px;margin-left:0px;margin-right:0px;padding:0px;padding-bottom:0px;padding-top:0px;padding-left:0px;padding-right:0px;box-sizing:border-box">Frequency: 2.4G</p></div></div>\r\n<div class="detailmodule_html"><div class="detail-desc-decorate-richtext"><p style="line-height:inherit;color:rgb(0, 0, 0);margin:0px;margin-bottom:0px;margin-top:0px;margin-left:0px;margin-right:0px;padding:0px;padding-bottom:0px;padding-top:0px;padding-left:0px;padding-right:0px;box-sizing:border-box">Channel: 4CH</p></div></div>\r\n<div class="detailmodule_html"><div class="detail-desc-decorate-richtext"><p style="line-height:inherit;color:rgb(0, 0, 0);margin:0px;margin-bottom:0px;margin-top:0px;margin-left:0px;margin-right:0px;padding:0px;padding-bottom:0px;padding-top:0px;padding-left:0px;padding-right:0px;box-sizing:border-box">Quadcopter Battery: (Included)</p></div></div>\r\n<div class="detailmodule_html"><div class="detail-desc-decorate-richtext"><p style="line-height:inherit;color:rgb(0, 0, 0);margin:0px;margin-bottom:0px;margin-top:0px;margin-left:0px;margin-right:0px;padding:0px;padding-bottom:0px;padding-top:0px;padding-left:0px;padding-right:0px;box-sizing:border-box">Transmitter Battery: 3x 1.5 AA Battery (NOT Included)</p>\n<p style="line-height:inherit;color:rgb(0, 0, 0);margin:0px;margin-bottom:0px;margin-top:0px;margin-left:0px;margin-right:0px;padding:0px;padding-bottom:0px;padding-top:0px;padding-left:0px;padding-right:0px;box-sizing:border-box">Features:</p>\n<div style="font-family:&quot;Open Sans&quot;, Roboto, Arial, Helvetica, sans-serif, SimSun;font-size:14px;font-weight:400;letter-spacing:normal;text-align:start;white-space:normal;color:rgb(34, 34, 34);margin:0px;margin-bottom:0px;margin-top:0px;margin-left:0px;margin-right:0px;padding:0px;padding-bottom:0px;padding-top:0px;padding-left:0px;padding-right:0px;box-sizing:content-box" class="detailmodule_text" align="start">\n <p style="line-height:inherit;color:rgb(0, 0, 0);margin:0px;margin-bottom:0px;margin-top:0px;margin-left:0px;margin-right:0px;padding:0px;padding-bottom:0px;padding-top:0px;padding-left:0px;padding-right:0px;box-sizing:border-box">- With foldable arms, small size, easy to carry.</p>\n</div>\n<div style="font-family:&quot;Open Sans&quot;, Roboto, Arial, Helvetica, sans-serif, SimSun;font-size:14px;font-weight:400;letter-spacing:normal;text-align:start;white-space:normal;color:rgb(34, 34, 34);margin:0px;margin-bottom:0px;margin-top:0px;margin-left:0px;margin-right:0px;padding:0px;padding-bottom:0px;padding-top:0px;padding-left:0px;padding-right:0px;box-sizing:content-box" class="detailmodule_text" align="start">\n <p style="line-height:inherit;color:rgb(0, 0, 0);margin:0px;margin-bottom:0px;margin-top:0px;margin-left:0px;margin-right:0px;padding:0px;padding-bottom:0px;padding-top:0px;padding-left:0px;padding-right:0px;box-sizing:border-box">- With altitude hold mode function provides stable flight.</p>\n</div>\n<div style="font-family:&quot;Open Sans&quot;, Roboto, Arial, Helvetica, sans-serif, SimSun;font-size:14px;font-weight:400;letter-spacing:normal;text-align:start;white-space:normal;color:rgb(34, 34, 34);margin:0px;margin-bottom:0px;margin-top:0px;margin-left:0px;margin-right:0px;padding:0px;padding-bottom:0px;padding-top:0px;padding-left:0px;padding-right:0px;box-sizing:content-box" class="detailmodule_text" align="start">\n <p style="line-height:inherit;color:rgb(0, 0, 0);margin:0px;margin-bottom:0px;margin-top:0px;margin-left:0px;margin-right:0px;padding:0px;padding-bottom:0px;padding-top:0px;padding-left:0px;padding-right:0px;box-sizing:border-box">- With wifi function can be connected APP, APK system to take pictures, video, real-time transmission through the phone camera image.</p>\n</div>\n<div style="font-family:&quot;Open Sans&quot;, Roboto, Arial, Helvetica, sans-serif, SimSun;font-size:14px;font-weight:400;letter-spacing:normal;text-align:start;white-space:normal;color:rgb(34, 34, 34);margin:0px;margin-bottom:0px;margin-top:0px;margin-left:0px;margin-right:0px;padding:0px;padding-bottom:0px;padding-top:0px;padding-left:0px;padding-right:0px;box-sizing:content-box" class="detailmodule_text" align="start">\n <p style="line-height:inherit;color:rgb(0, 0, 0);margin:0px;margin-bottom:0px;margin-top:0px;margin-left:0px;margin-right:0px;padding:0px;padding-bottom:0px;padding-top:0px;padding-left:0px;padding-right:0px;box-sizing:border-box">- There have 2 cameras can be choose. With 1080P or 4K wide angle camera give wide high denfinition pictures and video.</p>\n</div>\n<div style="font-family:&quot;Open Sans&quot;, Roboto, Arial, Helvetica, sans-serif, SimSun;font-size:14px;font-weight:400;letter-spacing:normal;text-align:start;white-space:normal;color:rgb(34, 34, 34);margin:0px;margin-bottom:0px;margin-top:0px;margin-left:0px;margin-right:0px;padding:0px;padding-bottom:0px;padding-top:0px;padding-left:0px;padding-right:0px;box-sizing:content-box" class="detailmodule_text" align="start">\n <p style="line-height:inherit;color:rgb(0, 0, 0);margin:0px;margin-bottom:0px;margin-top:0px;margin-left:0px;margin-right:0px;padding:0px;padding-bottom:0px;padding-top:0px;padding-left:0px;padding-right:0px;box-sizing:border-box">- With Headless Mode, no need to adjust the position of aircraft before flying .</p>\n</div>\n<div style="font-family:&quot;Open Sans&quot;, Roboto, Arial, Helvetica, sans-serif, SimSun;font-size:14px;font-weight:400;letter-spacing:normal;text-align:start;white-space:normal;color:rgb(34, 34, 34);margin:0px;margin-bottom:0px;margin-top:0px;margin-left:0px;margin-right:0px;padding:0px;padding-bottom:0px;padding-top:0px;padding-left:0px;padding-right:0px;box-sizing:content-box" class="detailmodule_text" align="start">\n <p style="line-height:inherit;color:rgb(0, 0, 0);margin:0px;margin-bottom:0px;margin-top:0px;margin-left:0px;margin-right:0px;padding:0px;padding-bottom:0px;padding-top:0px;padding-left:0px;padding-right:0px;box-sizing:border-box">- With One key to return function makes it easily to find the way home.</p>\n</div>\n<div style="font-family:&quot;Open Sans&quot;, Roboto, Arial, Helvetica, sans-serif, SimSun;font-size:14px;font-weight:400;letter-spacing:normal;text-align:start;white-space:normal;color:rgb(34, 34, 34);margin:0px;margin-bottom:0px;margin-top:0px;margin-left:0px;margin-right:0px;padding:0px;padding-bottom:0px;padding-top:0px;padding-left:0px;padding-right:0px;box-sizing:content-box" class="detailmodule_text" align="start">\n <p style="line-height:inherit;color:rgb(0, 0, 0);margin:0px;margin-bottom:0px;margin-top:0px;margin-left:0px;margin-right:0px;padding:0px;padding-bottom:0px;padding-top:0px;padding-left:0px;padding-right:0px;box-sizing:border-box">- Trajectory Flight. Draw a fligh way on the screen, and the drone would conduct an autonomous flight along the designated way.</p>\n</div></div></div>\r\n<div class="detailmodule_html"><div class="detail-desc-decorate-richtext"><p><img src="https://ae01.alicdn.com/kf/S9057f3fa99c84371b768d2b4df70c32b6.jpg" slate-data-type="image" /><img src="https://ae01.alicdn.com/kf/S96bd15bcbb764c41918565cf97a0561et.jpg" slate-data-type="image" /><img src="https://ae01.alicdn.com/kf/Sdc63638fcc98483c9ffea78e1f045d8bl.jpg" slate-data-type="image" /><img src="https://ae01.alicdn.com/kf/Sc936b75b5fbc4ffbbd141577ab5e7ea3y.jpg" slate-data-type="image" /><img src="https://ae01.alicdn.com/kf/Se404cdbf83f24730ba3a99d98df08c20e.jpg" slate-data-type="image" /><img src="https://ae01.alicdn.com/kf/S064fd4e449054c8091cc648ba2f0d01ba.jpg" slate-data-type="image" /></p></div></div>\r\n',
  },
  has_whole_sale: false,
  ae_item_properties: {
    ae_item_property: [
      {
        attr_name_id: 282401493,
        attr_value_id: 2467,
        attr_name: 'RTK Module（Real-time kinematic）',
        attr_value: 'No',
      },
      {
        attr_name_id: 2,
        attr_value_id: 203062806,
        attr_name: 'Brand Name',
        attr_value: 'other',
      },
      {
        attr_name_id: 200000623,
        attr_value_id: 201336196,
        attr_name: 'Flight Time',
        attr_value: '12min',
      },
      {
        attr_name_id: 282402896,
        attr_value_id: 2467,
        attr_name: 'Loudspeaker',
        attr_value: 'No',
      },
      {
        attr_name_id: 200000622,
        attr_value_id: 200003550,
        attr_name: 'Control Channels',
        attr_value: '4 channels',
      },
      {
        attr_name_id: 287377191,
        attr_value_id: 2467,
        attr_name: 'Built-in Display',
        attr_value: 'No',
      },
      {
        attr_name_id: 200007778,
        attr_value_id: 201336192,
        attr_name: 'Connectivity',
        attr_value: 'APP Controller',
      },
      {
        attr_name_id: 200007778,
        attr_value_id: 201336193,
        attr_name: 'Connectivity',
        attr_value: 'Remote Control',
      },
      {
        attr_name_id: 200007778,
        attr_value_id: 201336194,
        attr_name: 'Connectivity',
        attr_value: 'Wi-Fi Connection',
      },
      {
        attr_name_id: 200007777,
        attr_value_id: 201336187,
        attr_name: 'Camera Features',
        attr_value: '4K HD Video Recording',
      },
      {
        attr_name_id: 287213205,
        attr_value_id: -1,
        attr_name: 'Max Ascent Speed[m/s]',
        attr_value: '1',
      },
      {
        attr_name_id: 261281566,
        attr_value_id: -1,
        attr_name: 'Drone Battery Capacity',
        attr_value: '1800mAh',
      },
      {
        attr_name_id: 200000613,
        attr_value_id: -1,
        attr_name: 'Gyro',
        attr_value: 'NONE',
      },
      {
        attr_name_id: 200007781,
        attr_value_id: 349907,
        attr_name: 'FPV Operration',
        attr_value: 'Yes',
      },
      {
        attr_name_id: 200007780,
        attr_value_id: 201336206,
        attr_name: 'Camera Integration',
        attr_value: 'Camera Included',
      },
      {
        attr_name_id: 287380153,
        attr_value_id: -1,
        attr_name: 'Recommended age[Years]',
        attr_value: '14 +',
      },
      {
        attr_name_id: 24,
        attr_value_id: 201456721,
        attr_name: 'Pixels',
        attr_value: 'Below 0.4 million',
      },
      {
        attr_name_id: 200009712,
        attr_value_id: 201456685,
        attr_name: 'Optical Zoom',
        attr_value: '50x',
      },
      {
        attr_name_id: 282401097,
        attr_value_id: 2468,
        attr_name: 'Spotlight',
        attr_value: 'Yes',
      },
      {
        attr_name_id: 287211522,
        attr_value_id: -1,
        attr_name: 'Maximum Horizontal Speed[m/s]',
        attr_value: '2',
      },
      {
        attr_name_id: 287207732,
        attr_value_id: -1,
        attr_name: 'Maximum Altitude[m]',
        attr_value: '20',
      },
      {
        attr_name_id: 200006471,
        attr_value_id: 201456723,
        attr_name: 'Sensor Size',
        attr_value: '1/6.0 inches',
      },
      {
        attr_name_id: 200423261,
        attr_value_id: -1,
        attr_name: 'Internal Storage',
        attr_value: 'NONE',
      },
      {
        attr_name_id: 261281056,
        attr_value_id: 201335927,
        attr_name: 'Aircraf Operating Frequency',
        attr_value: '2.4 GHz',
      },
      {
        attr_name_id: 436,
        attr_value_id: -1,
        attr_name: 'Frequency',
        attr_value: '2.4G',
      },
      {
        attr_name_id: 200000607,
        attr_value_id: -1,
        attr_name: 'Main Rotor Diameter',
        attr_value: '18cm',
      },
      {
        attr_name_id: 287389206,
        attr_value_id: 2468,
        attr_name: 'Removable/Replaceable Battery',
        attr_value: 'Yes',
      },
      {
        attr_name_id: 287108011,
        attr_value_id: 1878411509,
        attr_name: 'Category',
        attr_value: 'Camera Drone',
      },
      {
        attr_name_id: 287203167,
        attr_value_id: -1,
        attr_name: 'Field of View[°]',
        attr_value: '120 °',
      },
      {
        attr_name_id: 261284432,
        attr_value_id: -1,
        attr_name: 'Drone Weight',
        attr_value: '200g',
      },
      {
        attr_name_id: 287204061,
        attr_value_id: -1,
        attr_name: 'Lens Aperture[f/Number]',
        attr_value: 'NONE',
      },
      {
        attr_name_id: 200000552,
        attr_value_id: -1,
        attr_name: 'Remote Distance',
        attr_value: '100m',
      },
      {
        attr_name_id: 200276267,
        attr_value_id: 349906,
        attr_name: 'GPS',
        attr_value: 'No',
      },
      {
        attr_name_id: 287372773,
        attr_value_id: 22796566637,
        attr_name: 'Video Maximum Resolution[Pixel X Pixel]',
        attr_value: '1080i/P（1920*1080）',
      },
      {
        attr_name_id: 287370095,
        attr_value_id: -1,
        attr_name: 'Depth[cm]',
        attr_value: '20',
      },
      {
        attr_name_id: 287212110,
        attr_value_id: -1,
        attr_name: 'Max Descent Speed[m/s]',
        attr_value: '2',
      },
      {
        attr_name_id: 282407558,
        attr_value_id: 2467,
        attr_name: 'Stobe',
        attr_value: 'No',
      },
      {
        attr_name_id: 248898182,
        attr_value_id: 12476517886,
        attr_name: 'Camera Mount Type',
        attr_value: 'Fixed Camera Mount',
      },
      {
        attr_name_id: 287206347,
        attr_value_id: -1,
        attr_name: 'Angle of View[Horizontal FoV X°, Vertical FoV X°, Diagonal FoV X°]',
        attr_value: '90 °',
      },
      {
        attr_name_id: 336833350,
        attr_value_id: 2467,
        attr_name: 'Equipped with Aerosol Spraing System/Spread Tank Volume',
        attr_value: 'No',
      },
      {
        attr_name_id: 287373686,
        attr_value_id: -1,
        attr_name: 'Display size["]',
        attr_value: '5.5in',
      },
      {
        attr_name_id: 287373687,
        attr_value_id: -1,
        attr_name: 'Remote Controller Battery Capacity[mAh]',
        attr_value: '3x 1.5 AA Battery',
      },
      {
        attr_name_id: 336840516,
        attr_value_id: 200007945,
        attr_name: 'Max Takeoff Weight',
        attr_value: '<1kg',
      },
      {
        attr_name_id: 200009651,
        attr_value_id: 349907,
        attr_name: 'Aerial Photography',
        attr_value: 'Yes',
      },
      {
        attr_name_id: 219,
        attr_value_id: 9441741844,
        attr_name: 'Origin',
        attr_value: 'Mainland China',
      },
      {
        attr_name_id: 348,
        attr_value_id: 351626,
        attr_name: 'Certification',
        attr_value: 'CE',
      },
      {
        attr_name_id: 348,
        attr_value_id: 360587,
        attr_name: 'Certification',
        attr_value: 'FCC',
      },
      {
        attr_name_id: 348,
        attr_value_id: 351628,
        attr_name: 'Certification',
        attr_value: 'RoHS',
      },
      {
        attr_name_id: 261281742,
        attr_value_id: 200003454,
        attr_name: 'Sensing Type',
        attr_value: 'None',
      },
      {
        attr_name_id: 287387518,
        attr_value_id: 100009342,
        attr_name: 'Expandable storage',
        attr_value: 'Other',
      },
      {
        attr_name_id: 287383934,
        attr_value_id: -1,
        attr_name: 'Height[cm]',
        attr_value: '6',
      },
      {
        attr_name_id: 261281741,
        attr_value_id: -1,
        attr_name: 'Max Flight Time',
        attr_value: '15min',
      },
      {
        attr_name_id: 287372481,
        attr_value_id: -1,
        attr_name: 'Width[cm]',
        attr_value: '20',
      },
      {
        attr_name_id: 261288819,
        attr_value_id: 200003454,
        attr_name: 'Camera Stabilization',
        attr_value: 'None',
      },
      {
        attr_name_id: 287377475,
        attr_value_id: -1,
        attr_name: 'Battery Weight[g]',
        attr_value: '20',
      },
      {
        attr_name_id: 336829689,
        attr_value_id: 27533667446,
        attr_name: 'Max Wind Speed Resistance',
        attr_value: '< 10 KM/H',
      },
      {
        attr_name_id: 261286240,
        attr_value_id: 17453573865,
        attr_name: 'Fps',
        attr_value: '24*fps',
      },
      {
        attr_name_id: 287378647,
        attr_value_id: -1,
        attr_name: 'Transmitter Power[dBm]',
        attr_value: '6.66wh',
      },
      {
        attr_name_id: 261289325,
        attr_value_id: 365210,
        attr_name: 'Transmission Range',
        attr_value: 'others',
      },
      {
        attr_name_id: -1,
        attr_name: 'Choice',
        attr_value: 'yes',
      },
    ],
  },
  ae_store_info: {
    store_id: 1102515566,
    shipping_speed_rating: '4.7',
    communication_rating: '4.6',
    store_name: 'BeeBeeBee Store',
    store_country_code: 'CN',
    item_as_described_rating: '4.5',
  },
};
