export const aliGetReviewsExp2 = {
  data: '',
  antiCrawlerContent:
    'Due to our system upgrades, this content is currently unavailable in your region.',
};

export const aliGetReviewsExp1 = {
  displayMessage: {
    reviewStructureAdditionalFeedback: 'Additional review',
    reviewStructureStars: 'Additional review',
    reviewStructureDefault: 'Sort by default',
    additional: 'Additional review',
    reviewStructureSellerReply: "Seller's reply",
    reviewStructureAdditionalReview: 'Additional review',
    reviewStructureLocalReview: 'Additional review',
    reviewStructureShowTranslate: 'Show original language',
    reviewStructureLatest: 'Sort by latest',
    reviewStructureReport: 'Report',
    reviewStructureAll: 'All',
    reviews: 'Reviews',
    reviewStructurePicReview: 'Additional review',
    reviewStructureHelpful: 'Helpful',
    reviewStructureSuggest: 'All from verified purchases',
    reviewStructureTranslate: 'Translate',
    reviewStructureStar: 'Star',
    numRatings: '80 ratings',
    reviewViewMore: 'View more',
    allRatings: 'All ratings',
  },
  data: {
    currentPage: 1,
    evaViewList: [
      {
        aigc: false,
        anonymous: false,
        buyerAddFbDays: 0,
        buyerCountry: 'US',
        buyerEval: 100,
        buyerFbSellerReplyTranslation: 'Dear friend, thank you for your five-star review',
        buyerFbType: {
          crowdSourcingPersonName: 'AliExpress Shopper',
          sourceLang: 'en',
          typeTranslationAccepted: 'crowdsourcing',
        },
        buyerFeedback: 'I am happy with my Labubu. Super 🥰',
        buyerName: 'U***r',
        buyerProductFeedBack: '',
        buyerTranslationFeedback: 'I am happy with my labubu. Super 🥰',
        downVoteCount: 0,
        evalDate: '24 Oct 2025',
        evaluationId: 60093185712131211n,
        evaluationIdStr: '60093185712131211',
        images: ['https://ae01.alicdn.com/kf/A9983b28c3c7642deb43dfc9d768cb855A.jpg'],
        independentSite: false,
        logistics: 'YunExpress Standard Shipping',
        reviewType: 'REVIEW',
        samePurchaseSuggestion: 'Buy the same',
        selectedReview: false,
        sellerReply: 'Dear friend, thank you for your five-star review',
        skuInfo: 'Color:Loyalty ',
        status: '1',
        thirdParty: false,
        thumbnails: [
          'https://ae01.alicdn.com/kf/A9983b28c3c7642deb43dfc9d768cb855A.jpg_220x220.jpg',
        ],
        trendyol: false,
        upVoteCount: 0,
      },
    ],
    filterInfo: {
      currentFilter: 'all',
      filterStatistic: [
        {
          filterCode: 'additional',
          filterCount: 4,
        },
        {
          filterCode: 'local',
          filterCount: 7,
        },
        {
          filterCode: 'with_personal',
          filterCount: 0,
        },
        {
          filterCode: 'image',
          filterCount: 15,
        },
        {
          filterCode: 'all',
          filterCount: 80,
        },
      ],
    },
    impressionDTOList: [
      {
        content: 'positive',
        emotion: 1,
        id: '1059570354307083765',
        num: 31,
        productId: 1005009900604826,
        type: 'impression',
      },
      {
        content: 'excellent quality',
        emotion: 1,
        id: '6765488166461671054',
        num: 30,
        productId: 1005009900604826,
        type: 'impression',
      },
      {
        content:
          'thank you for the guidance provided by the merchant the product can be used normally and is very good',
        emotion: 1,
        id: '963984345275662071',
        num: 27,
        productId: 1005009900604826,
        type: 'impression',
      },
      {
        content: 'disappointed',
        emotion: 1,
        id: '3274081470083934786',
        num: 24,
        productId: 1005009900604826,
        type: 'impression',
      },
      {
        content: 'very satisfied',
        emotion: 1,
        id: '528221151344410138',
        num: 23,
        productId: 1005009900604826,
        type: 'impression',
      },
      {
        content: 'disappointing',
        emotion: 1,
        id: '775982640703059352',
        num: 23,
        productId: 1005009900604826,
        type: 'impression',
      },
    ],
    pageSize: 1,
    productEvaluationStatistic: {
      evarageStar: 4.6,
      evarageStarRage: 92.4,
      fiveStarNum: 62,
      fiveStarRate: 78.5,
      fourStarNum: 7,
      fourStarRate: 8.9,
      negativeNum: 5,
      negativeRate: 6.3,
      neutralNum: 5,
      neutralRate: 6.3,
      oneStarNum: 5,
      oneStarRate: 6.3,
      positiveNum: 69,
      positiveRate: 87.4,
      threeStarNum: 5,
      threeStarRate: 6.3,
      totalNum: 79,
      twoStarNum: 0,
      twoStarRate: 0.0,
    },
    productType: 'ORDINARY',
    reviewStructuredLabelDTOList: [],
    totalNum: 80,
    totalPage: 80,
    version: '0.0.0',
  },
  helpful: {
    '60093185712131211': {
      showButton: 'yes',
      useful: 0,
      useless: 0,
    },
  },
};
